version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: whoiswho-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  web:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.web
    container_name: whoiswho-web
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis-data:

